### PR TITLE
Project maintenance

### PR DESCRIPTION
**Pull request by ldnunes**
Just some simple house cleaning changes.

### CODE REVIEW

**Comment by francois2metz** [comment]
:yellow_heart: Thanks for your contribution. :green_heart: 

Could you remove ruby-version and ruby-gemset ? No need to be there.

**Comment by ldnunes** [comment]
Sure thing!

Should I then simply remove the .rvmrc file instead?

**Comment by francois2metz** [comment]
Yep.

**Comment by francois2metz** [comment]
Thanks a lot/

**Pull request merged**
